version: '3'
services:
  app:
    networks:
      - compose-nodejs-redis-app
    deploy:
      replicas: 2
    image: mikebild/compose-nodejs-redis:1.0.0
    environment:
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    depends_on:
      - 'redis'
    ports:
      - '9090:80'
  redis:
    networks:
      - compose-nodejs-redis-app
    image: redis

networks:
  compose-nodejs-redis-app:
    external: true
