version: '3'
services:
  web:
    build: .
    environment:
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    ports:
      - '8080:8080'
    links:
      - 'redis'
    depends_on:
      - 'redis'
  redis:
    image: redis
