version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
http:
  addr: 0.0.0.0:5000
  secret: my-secret
  tls:
    certificate: /certs/domain.com.crt
    key: /certs/domain.com.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
